In [3]:
import numpy as np

a = np.random.randn(5)

In [4]:
# Rank1 array not matrix
print(a)

[ 0.74016612  0.75545194  0.99231601  0.78074696 -0.7007533 ]


In [5]:
print(a.shape)

(5,)


In [6]:
# Transpose is same
print(a.T)

[ 0.74016612  0.75545194  0.99231601  0.78074696 -0.7007533 ]


In [7]:
#dot product is a number

print(np.dot(a,a.T))

3.2038655963497065


In [8]:
 b = np.random.randn(5,1)

In [9]:
# It is a matrix
print(b)

[[ 0.30462369]
 [ 2.81481079]
 [-0.15124781]
 [ 1.08731139]
 [ 2.18319074]]


In [10]:
print(b.shape)

(5, 1)


In [11]:
print(b.T)

[[ 0.30462369  2.81481079 -0.15124781  1.08731139  2.18319074]]


In [12]:
# dot product is a matrix
print(np.dot(b, b.T))

[[ 0.09279559  0.85745805 -0.04607367  0.33122081  0.66505162]
 [ 0.85745805  7.92315979 -0.42573396  3.06057583  6.14526885]
 [-0.04607367 -0.42573396  0.0228759  -0.16445346 -0.33020281]
 [ 0.33122081  3.06057583 -0.16445346  1.18224605  2.37380815]
 [ 0.66505162  6.14526885 -0.33020281  2.37380815  4.7663218 ]]


In [16]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [15]:
c

array([[ 0.22392348, -0.10186243,  0.1198171 ],
       [ 0.26088897,  0.89893983, -0.63320468]])